### ISSUE TITLE
Update Astro dependency to V3

### ISSUE THREAD

**Issue by uranderu** [felix-berlin/astro-matomo#18]
**Is your feature request related to a problem? Please describe.**
Astro V3 is out today, currently upgrading my projects has been blocked because your package at the moment requires V2.

**Describe the solution you'd like**
Please update the dependency.

**Describe alternatives you've considered**
If someone would really want to, they could ignore the dependency issues with the right npm flags.

**Comment by felix-berlin** [comment]
Should be fixed by [v.1.4.0](https://github.com/felix-berlin/astro-matomo/releases/tag/v1.4.0)
